version: '3.1'

services:

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - './Mysql/Mysql:/var/lib/mysql'
      
  siren:
    build:
      context: .
      dockerfile: ./Siren/dockerfile
    restart: always
    ports:
      - 82:80
    volumes:
      - ./Siren/Siren:/var/www/html
    depends_on:
      - mysql
      
  solanin:
    image: ghost:latest
    restart: always
    ports:
      - 127.0.0.1:80:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: 
      database__connection__password: 
      database__connection__database: solanin
      url: 'http://localhost'
    volumes:
      - './Solanin/Solanin:/var/lib/ghost/content'
    depends_on:
      - mysql

  tsukiyo:
    build:
      context: .
      dockerfile: ./Tsukiyo/dockerfile
    restart: always
    ports:
      - 127.0.0.1:81:8000
    volumes:
      - './Tsukiyo/Tsukiyo/:/Tsukiyo'
    depends_on:
      - mysql
      
