FROM --platform=$BUILDPLATFORM python:latest AS builder
EXPOSE 8000
WORKDIR /app
COPY requirements.txt /app
RUN python -m pip install --upgrade pip
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /app
ENTRYPOINT ["python3"]
CMD ["manage.py", "makemigrations"]
CMD ["manage.py", "migrate"]
CMD ["manage.py", "runserver", "0.0.0.0:8000"]
