# Use an official PHP runtime as the base image
FROM php:8.1.2-apache

# Set the working directory in the container
WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    && docker-php-ext-install zip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Print current directory
RUN pwd

# Print directory contents
RUN ls -la

# Copy the composer.json and composer.lock files
COPY ./Siren/Siren/ .

# Install Laravel dependencies
RUN composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

# Install the Laravel installer
RUN composer global require laravel/installer

# Install PHP extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Set the composer bin directory in the system PATH
ENV PATH="/root/.composer/vendor/bin:${PATH}"

# Set the document root
RUN sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Enable the Apache rewrite module
RUN a2enmod rewrite

# Expose port 80
EXPOSE 80

# Start the Apache web server
CMD ["apache2-foreground"]
