FROM --platform=$BUILDPLATFORM python:latest AS builder
EXPOSE 8000
WORKDIR /Tsukiyo
COPY ./Tsukiyo/requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /Tsukiyo
ENTRYPOINT ["python3"]
CMD ["manage.py", "makemigrations"]
CMD ["manage.py", "migrate"]
CMD ["manage.py", "runserver", "0.0.0.0:8000"]
